export const ROLES = {
  APPLICANT: 'APPLICANT',
  POLICY_MANAGER: 'POLICY_MANAGER',
  MAIN_MANAGER: 'MAIN_MANAGER',
} as const;

export const STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
} as const;
